[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = [
  'npm ci --include=dev'
]

# Skip build phase - using tsx to run TypeScript directly
# [phases.build]
# cmds = [
#   'npm run build:bff'
# ]

[start]
cmd = 'cd apps/bff && npm start'

[variables]
NODE_ENV = 'production'
