[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
# Install from monorepo root
cmds = [
  'npm ci --include=dev'
]

[phases.build]
# Build the specific service
cmds = [
  'npm run build:bff'
]

[start]
cmd = 'cd apps/bff && npm start'

[variables]
NODE_ENV = 'production'